export enum ErrorCode {
  EMAIL_TAKEN = 'EMAIL_TAKEN',
  USERNAME_TAKEN = 'USERNAME_TAKEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  WRONG_PASSWORD = 'WRONG_PASSWORD',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  MEOW_NOT_FOUND = 'MEOW_NOT_FOUND',
  FILE_NOT_PROVIDED = 'FILE_NOT_PROVIDED',
  FILE_INVALID_TYPE = 'FILE_INVALID_TYPE',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  UNAUTHORIZED = 'UNAUTHORIZED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  VERIFICATION_TOKEN_INVALID = 'VERIFICATION_TOKEN_INVALID',
  INTERNAL_ERROR = 'INTERNAL_ERROR'
}
